from snakemake.utils import min_version

min_version("6.12.3")

configfile: "config/config.yaml"

import pandas as pd

SAMPLES = (
    pd.read_csv(config["samples"], dtype={"sample_name": str})
    .set_index("sample_name", drop=False)
    .sort_index()
    .sample_name
)

include: "rules/fastqc.smk"
include: "rules/cutadapt.smk"
include: "rules/trim.smk"
include: "rules/hisat2.smk"
include: "rules/featureCounts.smk"

# 设定需要保存的结果
rule all:
    input:
        expand("results/fastqc/{sample}_R1_fastqc.html", sample=SAMPLES),
        expand("results/fastqc/{sample}_R2_fastqc.html", sample=SAMPLES),
        expand("results/hisat2/{sample}.bam", sample=SAMPLES),
        expand("results/featureCounts/all.counts.txt")